deployment:
  tasks:
    # Deployment path for Node.js app
    - export NODE_DEPLOYPATH=/home/ethiobooking/abebeapi.ethiobooking.com/

    # Copy Node.js app files to deployment directory and install dependencies
    - /bin/cp -R server/* $NODE_DEPLOYPATH
    - cd $NODE_DEPLOYPATH
    - npm install

    # Restart Node.js app
    - /bin/killall -q node
    - npm start:prod &
