import { id } from "date-fns/locale";

export const footerLists = [
  {
    Top_destinations: [
      { id: 1, title: "Hotels in Addis Ababa", link: "/" },
      { id: 2, title: "Hotels in Addis Ababa", link: "/" },
      { id: 3, title: "Hotels in Addis Ababa", link: "/" },
      { id: 4, title: "Hotels in Addis Ababa", link: "/" },
      { id: 5, title: "Hotels in Addis Ababa", link: "/" },
      { id: 6, title: "Hotels in Addis Ababa", link: "/" },
      { id: 7, title: "Hotels in Addis Ababa", link: "/" },
      { id: 8, title: "Hotels in Addis Ababa", link: "/" },
      { id: 9, title: "Hotels in Addis Ababa", link: "/" },
      { id: 10, title: "Hotels in Addis Ababa", link: "/" },
      { id: 11, title: "Hotels in Addis Ababa", link: "/" },
      { id: 12, title: "Hotels in Addis Ababa", link: "/" },
      { id: 13, title: "Hotels in Addis Ababa", link: "/" },
      { id: 14, title: "Hotels in Addis Ababa", link: "/" },
      { id: 15, title: "Hotels in Addis Ababa", link: "/" },
      { id: 16, title: "Hotels in Addis Ababa", link: "/" },
      { id: 17, title: "Hotels in Addis Ababa", link: "/" },
      { id: 18, title: "Hotels in Addis Ababa", link: "/" },
    ],
  },
  {
    support_FAQ: [
      { id: 1, title: "Hotels in Addis Ababa", link: "/" },
      { id: 2, title: "Hotels in Addis Ababa", link: "/" },
      { id: 3, title: "Hotels in Addis Ababa", link: "/" },
      { id: 4, title: "Hotels in Addis Ababa", link: "/" },
      { id: 5, title: "Hotels in Addis Ababa", link: "/" },
      { id: 6, title: "Hotels in Addis Ababa", link: "/" },
      { id: 7, title: "Hotels in Addis Ababa", link: "/" },
      { id: 8, title: "Hotels in Addis Ababa", link: "/" },
      { id: 9, title: "Hotels in Addis Ababa", link: "/" },
      { id: 10, title: "Hotels in Addis Ababa", link: "/" },
      { id: 11, title: "Hotels in Addis Ababa", link: "/" },
      { id: 12, title: "Hotels in Addis Ababa", link: "/" },
      { id: 13, title: "Hotels in Addis Ababa", link: "/" },
      { id: 14, title: "Hotels in Addis Ababa", link: "/" },
      { id: 15, title: "Hotels in Addis Ababa", link: "/" },
      { id: 16, title: "Hotels in Addis Ababa", link: "/" },
      { id: 17, title: "Hotels in Addis Ababa", link: "/" },
      { id: 18, title: "Hotels in Addis Ababa", link: "/" },
    ],
  },
  {
    Policies: [
      { id: 1, title: "Hotels in Addis Ababa", link: "/" },
      { id: 2, title: "Hotels in Addis Ababa", link: "/" },
      { id: 3, title: "Hotels in Addis Ababa", link: "/" },
      { id: 4, title: "Hotels in Addis Ababa", link: "/" },
      { id: 5, title: "Hotels in Addis Ababa", link: "/" },
      { id: 6, title: "Hotels in Addis Ababa", link: "/" },
      { id: 7, title: "Hotels in Addis Ababa", link: "/" },
      { id: 8, title: "Hotels in Addis Ababa", link: "/" },
      { id: 9, title: "Hotels in Addis Ababa", link: "/" },
      { id: 10, title: "Hotels in Addis Ababa", link: "/" },
      { id: 11, title: "Hotels in Addis Ababa", link: "/" },
      { id: 12, title: "Hotels in Addis Ababa", link: "/" },
      { id: 13, title: "Hotels in Addis Ababa", link: "/" },
      { id: 14, title: "Hotels in Addis Ababa", link: "/" },
      { id: 15, title: "Hotels in Addis Ababa", link: "/" },
      { id: 16, title: "Hotels in Addis Ababa", link: "/" },
      { id: 17, title: "Hotels in Addis Ababa", link: "/" },
      { id: 18, title: "Hotels in Addis Ababa", link: "/" },
    ],
  },
  {
    other_policies: [
      { id: 1, title: "Hotels in Addis Ababa", link: "/" },
      { id: 2, title: "Hotels in Addis Ababa", link: "/" },
      { id: 3, title: "Hotels in Addis Ababa", link: "/" },
      { id: 4, title: "Hotels in Addis Ababa", link: "/" },
      { id: 5, title: "Hotels in Addis Ababa", link: "/" },
      { id: 6, title: "Hotels in Addis Ababa", link: "/" },
      { id: 7, title: "Hotels in Addis Ababa", link: "/" },
      { id: 8, title: "Hotels in Addis Ababa", link: "/" },
      { id: 9, title: "Hotels in Addis Ababa", link: "/" },
      { id: 10, title: "Hotels in Addis Ababa", link: "/" },
      { id: 11, title: "Hotels in Addis Ababa", link: "/" },
      { id: 12, title: "Hotels in Addis Ababa", link: "/" },
      { id: 13, title: "Hotels in Addis Ababa", link: "/" },
      { id: 14, title: "Hotels in Addis Ababa", link: "/" },
      { id: 15, title: "Hotels in Addis Ababa", link: "/" },
      { id: 16, title: "Hotels in Addis Ababa", link: "/" },
      { id: 17, title: "Hotels in Addis Ababa", link: "/" },
      { id: 18, title: "Hotels in Addis Ababa", link: "/" },
    ],
  },
];
