name:  Deploy website on push

on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: 🔨 Build Project
        run: |
          cd client
          npm install
          export VITE_API_URL=${{ secrets.VITE_API_URL }}
          export VITE_MAP_API_KEY=${{ secrets.VITE_MAP_API_KEY }}
          npm run build

      - name: Deploy React App to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.ethiobooking.com
          username: abebe@ethiobooking.com
          password: ${{ secrets.FTP_FRONTEND_PASSWORD }}
          server-dir: /abebe.ethiobooking.com/
          local-dir: client/dist/
          exclude: ".git,.github,node_modules"

      - name: Deploy Node.js Server-Side App to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.ethiobooking.com
          username: abebeserver@ethiobooking.com
          password: ${{ secrets.FTP_BACKEND_PASSWORD }}
          server-dir: /abebeapi.ethiobooking.com/
          local-dir: server/
          exclude: ".git,.github,node_modules"
